name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello ${{ secrets.USER_NAME }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build, ${{ vars.USER_NAME }}
          echo test, and deploy your project.
